export const homeURL: string = "/"
export const registerURL: string = "/register"
export const loginURL: string = "/login"
export const profileURL: string = "/profile"
export const reserveURL: string = "/reserve/:movieId"
export const adminURL: string = "/admin"
export const tourURL: string = "/tour/:tourID"